Status:
    type: entity
    table: status
    indexes:
        fk_status_status_idx:
            columns:
                - next
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
    manyToOne:
        next:
            targetEntity: Status
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                next:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
